"""empty message

Revision ID: 56a151710364
Revises: b74f67f52ae5
Create Date: 2021-08-16 10:40:01.550900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a151710364'
down_revision = 'b74f67f52ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'about_me', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'about_me', type_='unique')
    # ### end Alembic commands ###
